#!/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &

# <Xrandr>
source ~/.config/bspwm/monitors
source ~/.config/bspwm/huion
# </Xrandr>

# <general config>
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# </general config>

# <border>
bspc config border_width         1
bspc config window_gap          12

bspc config active_border_color \#414141
bspc config normal_border_color \#414141
bspc config focused_border_color \#d0d0d0
# </border>

# <BSPWM rules>
bspc rule -a Zathura    state=tiled
bspc rule -a mpv        state=floating
# </BSPWM rules>

# <design>
setxkbmap -layout dk
xsetroot -cursor_name left_ptr &

feh --bg-fill ~/Git/Dotfiles/wallpapers/cow.jpg
picom -b --config ~/.config/picom/picom.conf &

~/.config/polybar/launch.sh &
# </design>
