#!/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &

# <general config>
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# </general config>

# <border>
bspc config border_width         1
bspc config window_gap          12

bspc config active_border_color \#414141
bspc config normal_border_color \#414141
bspc config focused_border_color \#d0d0d0
# </border>

# <BSPWM rules>
bspc rule -a Zathura    state=tiled
bspc rule -a mpv        state=floating
# </BSPWM rules>

# <monitor setup>
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-0')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr \
        --output HDMI-0 \
            --primary \
            --mode 1920x1080 \
            --fbmm 598x336 \
            --rate 144 \
            --rotate normal \
        --output eDP-1-1 \
            --mode 1920x1080 \
            --fbmm 344x194 \
            --rotate normal \
            --right-of HDMI-0

    bspc monitor HDMI-0     -d 1 2 3 4
    bspc monitor eDP-1-1    -d 5 6 7 8
else
    xrandr \
        --output eDP-1-1 \
            --primary \
            --mode 1920x1080 \
            --fbmm 344x194 \
            --rotate normal
    
    bspc monitor eDP-1-1 -d 1 2 3 4
fi

xrandr --dpi 96
# </monitor setup>

# <tablet setup>
MONITOR="HDMI-0"
PAD_NAME='Tablet Monitor'

ID_STYLUS=`xinput | grep -m 1 "Tablet Monitor stylus" | cut -d '=' -f 2 | cut -f 1`

xinput map-to-output $ID_STYLUS $MONITOR
# </tablet setup>

# <design>
xsetroot -cursor_name left_ptr &
feh --bg-fill $HOME/Git-projects/Dotfiles/wallpapers/cow.jpg

picom -b --config $HOME/.config/picom/picom.conf & 

xsetroot -cursor_name left_ptr &
setxkbmap -layout dk

$HOME/.config/polybar/launch.sh &
# </design>
